import { Track } from '../types';

export const FALLBACK_TRACKS: Omit<Track, 'id' | 'duration' | 'coverArt'>[] = [
  {
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    album: 'After Hours',
    genre: 'Pop',
    year: 2019,
  },
  {
    title: 'Flowers',
    artist: 'Miley Cyrus',
    album: 'Endless Summer Vacation',
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'Stay',
    artist: 'The Kid LAROI & Justin Bieber',
    album: 'F*CK LOVE 3: OVER YOU',
    genre: 'Pop',
    year: 2021,
  },
  { title: 'Levitating', artist: 'Dua Lipa', album: 'Future Nostalgia', genre: 'Pop', year: 2020 },
  {
    title: 'Watermelon Sugar',
    artist: 'Harry Styles',
    album: 'Fine Line',
    genre: 'Pop',
    year: 2019,
  },
  {
    title: 'Save Your Tears',
    artist: 'The Weeknd',
    album: 'After Hours',
    genre: 'Pop',
    year: 2020,
  },
  { title: 'Good 4 U', artist: 'Olivia Rodrigo', album: 'SOUR', genre: 'Pop Rock', year: 2021 },
  {
    title: 'Heat Waves',
    artist: 'Glass Animals',
    album: 'Dreamland',
    genre: 'Indie Pop',
    year: 2020,
  },
  { title: 'Anti-Hero', artist: 'Taylor Swift', album: 'Midnights', genre: 'Pop', year: 2022 },
  { title: 'As It Was', artist: 'Harry Styles', album: "Harry's House", genre: 'Pop', year: 2022 },
  {
    title: 'Sunflower',
    artist: 'Post Malone & Swae Lee',
    album: 'Spider-Man: Into the Spider-Verse',
    genre: 'Hip Hop',
    year: 2018,
  },
  { title: 'Shape of You', artist: 'Ed Sheeran', album: '÷ (Divide)', genre: 'Pop', year: 2017 },
  {
    title: 'Rockstar',
    artist: 'Post Malone ft. 21 Savage',
    album: 'Beerbongs & Bentleys',
    genre: 'Hip Hop',
    year: 2017,
  },
  {
    title: 'One Dance',
    artist: 'Drake ft. WizKid & Kyla',
    album: 'Views',
    genre: 'Afrobeats',
    year: 2016,
  },
  {
    title: 'Someone You Loved',
    artist: 'Lewis Capaldi',
    album: 'Divinely Uninspired to a Hellish Extent',
    genre: 'Pop',
    year: 2019,
  },
  {
    title: 'Señorita',
    artist: 'Shawn Mendes & Camila Cabello',
    album: 'Shawn Mendes',
    genre: 'Pop',
    year: 2019,
  },
  {
    title: 'Uptown Funk',
    artist: 'Mark Ronson ft. Bruno Mars',
    album: 'Uptown Special',
    genre: 'Funk',
    year: 2014,
  },
  {
    title: 'Old Town Road',
    artist: 'Lil Nas X ft. Billy Ray Cyrus',
    album: '7',
    genre: 'Country Rap',
    year: 2019,
  },
  {
    title: 'Bohemian Rhapsody',
    artist: 'Queen',
    album: 'A Night at the Opera',
    genre: 'Rock',
    year: 1975,
  },
  {
    title: 'Smooth',
    artist: 'Santana ft. Rob Thomas',
    album: 'Supernatural',
    genre: 'Rock',
    year: 1999,
  },
  { title: 'Hey Jude', artist: 'The Beatles', album: 'Hey Jude', genre: 'Rock', year: 1968 },
  {
    title: 'I Will Always Love You',
    artist: 'Whitney Houston',
    album: 'The Bodyguard',
    genre: 'R&B',
    year: 1992,
  },
  { title: 'Rolling in the Deep', artist: 'Adele', album: '21', genre: 'Pop', year: 2010 },
  {
    title: 'Party Rock Anthem',
    artist: 'LMFAO',
    album: 'Sorry for Party Rocking',
    genre: 'Electronic',
    year: 2011,
  },
  { title: 'Happy', artist: 'Pharrell Williams', album: 'G I R L', genre: 'Pop', year: 2013 },
  {
    title: 'Despacito',
    artist: 'Luis Fonsi & Daddy Yankee',
    album: 'Vida',
    genre: 'Latin Pop',
    year: 2017,
  },
  { title: 'Shake It Off', artist: 'Taylor Swift', album: '1989', genre: 'Pop', year: 2014 },
  {
    title: 'See You Again',
    artist: 'Wiz Khalifa ft. Charlie Puth',
    album: 'Furious 7',
    genre: 'Hip Hop',
    year: 2015,
  },
  { title: 'Lose Yourself', artist: 'Eminem', album: '8 Mile', genre: 'Hip Hop', year: 2002 },
  {
    title: 'Dance Monkey',
    artist: 'Tones and I',
    album: 'The Kids Are Coming',
    genre: 'Pop',
    year: 2019,
  },
  { title: 'Vampire', artist: 'Olivia Rodrigo', album: 'GUTS', genre: 'Pop Rock', year: 2023 },
  { title: 'Cruel Summer', artist: 'Taylor Swift', album: 'Lover', genre: 'Pop', year: 2019 },
  { title: 'Kill Bill', artist: 'SZA', album: 'SOS', genre: 'R&B', year: 2022 },
  { title: 'Bad Habit', artist: 'Steve Lacy', album: 'Gemini Rights', genre: 'R&B', year: 2022 },
  { title: 'About Damn Time', artist: 'Lizzo', album: 'Special', genre: 'Pop', year: 2022 },
  { title: 'Unholy', artist: 'Sam Smith & Kim Petras', album: 'Gloria', genre: 'Pop', year: 2022 },
  {
    title: 'Calm Down',
    artist: 'Rema & Selena Gomez',
    album: 'Rave & Roses',
    genre: 'Afrobeats',
    year: 2022,
  },
  {
    title: 'Last Night',
    artist: 'Morgan Wallen',
    album: 'One Thing at a Time',
    genre: 'Country',
    year: 2023,
  },
  {
    title: 'Running Up That Hill',
    artist: 'Kate Bush',
    album: 'Hounds of Love',
    genre: 'Pop',
    year: 1985,
  },
  { title: 'Glimpse of Us', artist: 'Joji', album: 'SMITHEREENS', genre: 'Pop', year: 2022 },
  { title: 'Break My Soul', artist: 'Beyoncé', album: 'RENAISSANCE', genre: 'Dance', year: 2022 },
  {
    title: 'Super Freaky Girl',
    artist: 'Nicki Minaj',
    album: 'Pink Friday 2',
    genre: 'Hip Hop',
    year: 2022,
  },
  {
    title: 'First Class',
    artist: 'Jack Harlow',
    album: 'Come Home the Kids Miss You',
    genre: 'Hip Hop',
    year: 2022,
  },
  { title: 'Sunroof', artist: 'Nicky Youre & dazy', album: 'Sunroof', genre: 'Pop', year: 2022 },
  {
    title: 'I Like You',
    artist: 'Post Malone ft. Doja Cat',
    album: 'Twelve Carat Toothache',
    genre: 'Pop',
    year: 2022,
  },
  { title: 'Big Energy', artist: 'Latto', album: '777', genre: 'Hip Hop', year: 2022 },
  { title: 'Boyfriend', artist: 'Dove Cameron', album: 'Boyfriend', genre: 'Pop', year: 2022 },
  { title: 'Woman', artist: 'Doja Cat', album: 'Planet Her', genre: 'Pop', year: 2021 },
  {
    title: 'Industry Baby',
    artist: 'Lil Nas X & Jack Harlow',
    album: 'MONTERO',
    genre: 'Hip Hop',
    year: 2021,
  },
  {
    title: 'Wait For U',
    artist: 'Future ft. Drake & Tems',
    album: 'I NEVER LIKED YOU',
    genre: 'Hip Hop',
    year: 2022,
  },
  { title: 'Ghost', artist: 'Justin Bieber', album: 'Justice', genre: 'Pop', year: 2021 },
  {
    title: 'Late Night Talking',
    artist: 'Harry Styles',
    album: "Harry's House",
    genre: 'Pop',
    year: 2022,
  },
  {
    title: 'Something in the Orange',
    artist: 'Zach Bryan',
    album: 'American Heartbreak',
    genre: 'Country',
    year: 2022,
  },
  { title: 'Unstoppable', artist: 'Sia', album: 'This Is Acting', genre: 'Pop', year: 2016 },
  {
    title: 'Until I Found You',
    artist: 'Stephen Sanchez',
    album: 'Angel Face',
    genre: 'Pop',
    year: 2022,
  },
  {
    title: 'Left and Right',
    artist: 'Charlie Puth ft. Jung Kook',
    album: 'CHARLIE',
    genre: 'Pop',
    year: 2022,
  },
  {
    title: 'Wasted on You',
    artist: 'Morgan Wallen',
    album: 'One Thing at a Time',
    genre: 'Country',
    year: 2023,
  },
  {
    title: 'Tití Me Preguntó',
    artist: 'Bad Bunny',
    album: 'Un Verano Sin Ti',
    genre: 'Latin',
    year: 2022,
  },
  {
    title: 'Ella Baila Sola',
    artist: 'Eslabon Armado & Peso Pluma',
    album: 'DESVELADO',
    genre: 'Regional Mexican',
    year: 2023,
  },
  {
    title: 'Boys a Liar Pt. 2',
    artist: 'PinkPantheress & Ice Spice',
    album: 'Boys a Liar Pt. 2',
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'Paint the Town Red',
    artist: 'Doja Cat',
    album: 'Scarlet',
    genre: 'Hip Hop',
    year: 2023,
  },
  { title: 'Fast Car', artist: 'Luke Combs', album: "Gettin' Old", genre: 'Country', year: 2023 },
  {
    title: 'What Was I Made For?',
    artist: 'Billie Eilish',
    album: 'Barbie: The Album',
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'Rich Men North of Richmond',
    artist: 'Oliver Anthony Music',
    album: 'Rich Men North of Richmond',
    genre: 'Folk',
    year: 2023,
  },
  {
    title: 'I Remember Everything',
    artist: 'Zach Bryan ft. Kacey Musgraves',
    album: 'Zach Bryan',
    genre: 'Country',
    year: 2023,
  },
  {
    title: 'Thinkin Bout Me',
    artist: 'Morgan Wallen',
    album: 'One Thing at a Time',
    genre: 'Country',
    year: 2023,
  },
  { title: 'Fukumean', artist: 'Gunna', album: 'a Gift & a Curse', genre: 'Hip Hop', year: 2023 },
  {
    title: 'Dance the Night',
    artist: 'Dua Lipa',
    album: 'Barbie: The Album',
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'Barbie World',
    artist: 'Nicki Minaj & Ice Spice',
    album: 'Barbie: The Album',
    genre: 'Hip Hop',
    year: 2023,
  },
  { title: 'Seven', artist: 'Jung Kook ft. Latto', album: 'Seven', genre: 'Pop', year: 2023 },
  {
    title: 'Popular',
    artist: 'The Weeknd, Playboi Carti & Madonna',
    album: 'The Idol',
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'Meltdown',
    artist: 'Travis Scott ft. Drake',
    album: 'UTOPIA',
    genre: 'Hip Hop',
    year: 2023,
  },
  {
    title: 'Feather',
    artist: 'Sabrina Carpenter',
    album: "emails i can't send fwd:",
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'Get Him Back!',
    artist: 'Olivia Rodrigo',
    album: 'GUTS',
    genre: 'Pop Rock',
    year: 2023,
  },
  {
    title: 'Used to Be Young',
    artist: 'Miley Cyrus',
    album: 'Used to Be Young',
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'Bad Idea Right?',
    artist: 'Olivia Rodrigo',
    album: 'GUTS',
    genre: 'Pop Rock',
    year: 2023,
  },
  {
    title: 'Better Place',
    artist: '*NSYNC',
    album: 'Trolls Band Together',
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'Need a Favor',
    artist: 'Jelly Roll',
    album: 'Whitsitt Chapel',
    genre: 'Country',
    year: 2023,
  },
  {
    title: 'Calling',
    artist: 'Metro Boomin ft. Swae Lee & NAV',
    album: 'Spider-Man: Across the Spider-Verse',
    genre: 'Hip Hop',
    year: 2023,
  },
  {
    title: 'Lovin on Me',
    artist: 'Jack Harlow',
    album: 'Lovin on Me',
    genre: 'Hip Hop',
    year: 2023,
  },
  { title: 'Water', artist: 'Tyla', album: 'Water', genre: 'Afrobeats', year: 2023 },
  { title: 'Agora Hills', artist: 'Doja Cat', album: 'Scarlet', genre: 'Pop', year: 2023 },
  { title: 'Strangers', artist: 'Kenya Grace', album: 'Strangers', genre: 'Pop', year: 2023 },
  {
    title: 'My Love Mine All Mine',
    artist: 'Mitski',
    album: 'The Land Is Inhospitable and So Are We',
    genre: 'Indie Pop',
    year: 2023,
  },
  { title: 'Greedy', artist: 'Tate McRae', album: 'Greedy', genre: 'Pop', year: 2023 },
  { title: 'Houdini', artist: 'Dua Lipa', album: 'Houdini', genre: 'Pop', year: 2023 },
  {
    title: 'Lose Control',
    artist: 'Teddy Swims',
    album: "I've Tried Everything but Therapy",
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'Is It Over Now?',
    artist: 'Taylor Swift',
    album: "1989 (Taylor's Version)",
    genre: 'Pop',
    year: 2023,
  },
  {
    title: "Now That We Don't Talk",
    artist: 'Taylor Swift',
    album: "1989 (Taylor's Version)",
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'Slime You Out',
    artist: 'Drake ft. SZA',
    album: 'For All the Dogs',
    genre: 'Hip Hop',
    year: 2023,
  },
  { title: 'Daylight', artist: 'David Kushner', album: 'Daylight', genre: 'Pop', year: 2023 },
  { title: 'cardigan', artist: 'Taylor Swift', album: 'folklore', genre: 'Indie Folk', year: 2020 },
  { title: 'august', artist: 'Taylor Swift', album: 'folklore', genre: 'Indie Folk', year: 2020 },
  { title: 'Espresso', artist: 'Sabrina Carpenter', album: 'Espresso', genre: 'Pop', year: 2024 },
  {
    title: 'Beautiful Things',
    artist: 'Benson Boone',
    album: 'Beautiful Things',
    genre: 'Pop',
    year: 2024,
  },
  {
    title: 'Not Like Us',
    artist: 'Kendrick Lamar',
    album: 'Not Like Us',
    genre: 'Hip Hop',
    year: 2024,
  },
  {
    title: 'I Had Some Help',
    artist: 'Post Malone ft. Morgan Wallen',
    album: 'I Had Some Help',
    genre: 'Country',
    year: 2024,
  },
  {
    title: 'A Bar Song (Tipsy)',
    artist: 'Shaboozey',
    album: 'A Bar Song (Tipsy)',
    genre: 'Country',
    year: 2024,
  },
  {
    title: 'Million Dollar Baby',
    artist: 'Tommy Richman',
    album: 'Million Dollar Baby',
    genre: 'Hip Hop',
    year: 2024,
  },
  {
    title: 'BIRDS OF A FEATHER',
    artist: 'Billie Eilish',
    album: 'HIT ME HARD AND SOFT',
    genre: 'Pop',
    year: 2024,
  },
  { title: 'Too Sweet', artist: 'Hozier', album: 'Unheard', genre: 'Indie Rock', year: 2024 },
  {
    title: 'Please Please Please',
    artist: 'Sabrina Carpenter',
    album: 'Please Please Please',
    genre: 'Pop',
    year: 2024,
  },
  {
    title: 'Fortnight',
    artist: 'Taylor Swift ft. Post Malone',
    album: 'THE TORTURED POETS DEPARTMENT',
    genre: 'Pop',
    year: 2024,
  },
  {
    title: 'Good Luck, Babe!',
    artist: 'Chappell Roan',
    album: 'Good Luck, Babe!',
    genre: 'Pop',
    year: 2024,
  },
  {
    title: 'Stick Season',
    artist: 'Noah Kahan',
    album: 'Stick Season',
    genre: 'Folk Pop',
    year: 2022,
  },
  {
    title: 'Lil Boo Thang',
    artist: 'Paul Russell',
    album: 'Lil Boo Thang',
    genre: 'Pop',
    year: 2023,
  },
  {
    title: "we can't be friends",
    artist: 'Ariana Grande',
    album: 'eternal sunshine',
    genre: 'Pop',
    year: 2024,
  },
  { title: 'Saturn', artist: 'SZA', album: 'Saturn', genre: 'R&B', year: 2024 },
  {
    title: "TEXAS HOLD 'EM",
    artist: 'Beyoncé',
    album: 'COWBOY CARTER',
    genre: 'Country',
    year: 2024,
  },
  {
    title: 'Like That',
    artist: 'Future, Metro Boomin & Kendrick Lamar',
    album: "WE DON'T TRUST YOU",
    genre: 'Hip Hop',
    year: 2024,
  },
  {
    title: 'LUNCH',
    artist: 'Billie Eilish',
    album: 'HIT ME HARD AND SOFT',
    genre: 'Pop',
    year: 2024,
  },
  { title: 'Pink Skies', artist: 'Zach Bryan', album: 'Pink Skies', genre: 'Country', year: 2024 },
  {
    title: 'Slow It Down',
    artist: 'Benson Boone',
    album: 'Fireworks & Rollerblades',
    genre: 'Pop',
    year: 2024,
  },
  { title: 'Austin', artist: 'Dasha', album: 'Austin', genre: 'Country', year: 2024 },
  {
    title: 'I Can Do It With a Broken Heart',
    artist: 'Taylor Swift',
    album: 'THE TORTURED POETS DEPARTMENT',
    genre: 'Pop',
    year: 2024,
  },
  {
    title: 'One of the Girls',
    artist: 'The Weeknd, JENNIE & Lily-Rose Depp',
    album: 'The Idol',
    genre: 'R&B',
    year: 2023,
  },
  { title: 'End of Beginning', artist: 'Djo', album: 'DECIDE', genre: 'Alternative', year: 2022 },
  {
    title: 'Where the Wild Things Are',
    artist: 'Luke Combs',
    album: "Gettin' Old",
    genre: 'Country',
    year: 2023,
  },
];
