import { Track } from '../types';

export const FALLBACK_TRACKS: Omit<Track, 'id' | 'coverArt'>[] = [
  {
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    album: 'After Hours',
    duration: 200,
    genre: 'Pop',
    year: 2019,
  },
  {
    title: 'Flowers',
    artist: 'Miley Cyrus',
    album: 'Endless Summer Vacation',
    duration: 192,
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'Stay',
    artist: 'The Kid LAROI & Justin Bieber',
    album: 'F*CK LOVE 3: OVER YOU',
    duration: 145,
    genre: 'Pop',
    year: 2021,
  },
  {
    title: 'Levitating',
    artist: 'Dua Lipa',
    album: 'Future Nostalgia',
    duration: 203,
    genre: 'Pop',
    year: 2020,
  },
  {
    title: 'Watermelon Sugar',
    artist: 'Harry Styles',
    album: 'Fine Line',
    duration: 174,
    genre: 'Pop',
    year: 2019,
  },
  {
    title: 'Save Your Tears',
    artist: 'The Weeknd',
    album: 'After Hours',
    duration: 215,
    genre: 'Pop',
    year: 2020,
  },
  {
    title: 'Good 4 U',
    artist: 'Olivia Rodrigo',
    album: 'SOUR',
    duration: 178,
    genre: 'Pop Rock',
    year: 2021,
  },
  {
    title: 'Heat Waves',
    artist: 'Glass Animals',
    album: 'Dreamland',
    duration: 238,
    genre: 'Indie Pop',
    year: 2020,
  },
  {
    title: 'Anti-Hero',
    artist: 'Taylor Swift',
    album: 'Midnights',
    duration: 200,
    genre: 'Pop',
    year: 2022,
  },
  {
    title: 'As It Was',
    artist: 'Harry Styles',
    album: "Harry's House",
    duration: 167,
    genre: 'Pop',
    year: 2022,
  },
  {
    title: 'Sunflower',
    artist: 'Post Malone & Swae Lee',
    album: 'Spider-Man: Into the Spider-Verse',
    duration: 158,
    genre: 'Hip Hop',
    year: 2018,
  },
  {
    title: 'Shape of You',
    artist: 'Ed Sheeran',
    album: '÷ (Divide)',
    duration: 233,
    genre: 'Pop',
    year: 2017,
  },
  {
    title: 'Rockstar',
    artist: 'Post Malone ft. 21 Savage',
    album: 'Beerbongs & Bentleys',
    duration: 218,
    genre: 'Hip Hop',
    year: 2017,
  },
  {
    title: 'One Dance',
    artist: 'Drake ft. WizKid & Kyla',
    album: 'Views',
    duration: 173,
    genre: 'Afrobeats',
    year: 2016,
  },
  {
    title: 'Someone You Loved',
    artist: 'Lewis Capaldi',
    album: 'Divinely Uninspired to a Hellish Extent',
    duration: 182,
    genre: 'Pop',
    year: 2019,
  },
  {
    title: 'Señorita',
    artist: 'Shawn Mendes & Camila Cabello',
    album: 'Shawn Mendes',
    duration: 190,
    genre: 'Pop',
    year: 2019,
  },
  {
    title: 'Uptown Funk',
    artist: 'Mark Ronson ft. Bruno Mars',
    album: 'Uptown Special',
    duration: 270,
    genre: 'Funk',
    year: 2014,
  },
  {
    title: 'Old Town Road',
    artist: 'Lil Nas X ft. Billy Ray Cyrus',
    album: '7',
    duration: 157,
    genre: 'Country Rap',
    year: 2019,
  },
  {
    title: 'Bohemian Rhapsody',
    artist: 'Queen',
    album: 'A Night at the Opera',
    duration: 355,
    genre: 'Rock',
    year: 1975,
  },
  {
    title: 'Smooth',
    artist: 'Santana ft. Rob Thomas',
    album: 'Supernatural',
    duration: 295,
    genre: 'Rock',
    year: 1999,
  },
  {
    title: 'Hey Jude',
    artist: 'The Beatles',
    album: 'Hey Jude',
    duration: 431,
    genre: 'Rock',
    year: 1968,
  },
  {
    title: 'I Will Always Love You',
    artist: 'Whitney Houston',
    album: 'The Bodyguard',
    duration: 273,
    genre: 'R&B',
    year: 1992,
  },
  {
    title: 'Rolling in the Deep',
    artist: 'Adele',
    album: '21',
    duration: 228,
    genre: 'Pop',
    year: 2010,
  },
  {
    title: 'Party Rock Anthem',
    artist: 'LMFAO',
    album: 'Sorry for Party Rocking',
    duration: 263,
    genre: 'Electronic',
    year: 2011,
  },
  {
    title: 'Happy',
    artist: 'Pharrell Williams',
    album: 'G I R L',
    duration: 233,
    genre: 'Pop',
    year: 2013,
  },
  {
    title: 'Despacito',
    artist: 'Luis Fonsi & Daddy Yankee',
    album: 'Vida',
    duration: 229,
    genre: 'Latin Pop',
    year: 2017,
  },
  {
    title: 'Shake It Off',
    artist: 'Taylor Swift',
    album: '1989',
    duration: 219,
    genre: 'Pop',
    year: 2014,
  },
  {
    title: 'See You Again',
    artist: 'Wiz Khalifa ft. Charlie Puth',
    album: 'Furious 7',
    duration: 229,
    genre: 'Hip Hop',
    year: 2015,
  },
  {
    title: 'Lose Yourself',
    artist: 'Eminem',
    album: '8 Mile',
    duration: 326,
    genre: 'Hip Hop',
    year: 2002,
  },
  {
    title: 'Dance Monkey',
    artist: 'Tones and I',
    album: 'The Kids Are Coming',
    duration: 209,
    genre: 'Pop',
    year: 2019,
  },
  {
    title: 'Vampire',
    artist: 'Olivia Rodrigo',
    album: 'GUTS',
    duration: 218,
    genre: 'Pop Rock',
    year: 2023,
  },
  {
    title: 'Cruel Summer',
    artist: 'Taylor Swift',
    album: 'Lover',
    duration: 178,
    genre: 'Pop',
    year: 2019,
  },
  { title: 'Kill Bill', artist: 'SZA', album: 'SOS', duration: 155, genre: 'R&B', year: 2022 },
  {
    title: 'Bad Habit',
    artist: 'Steve Lacy',
    album: 'Gemini Rights',
    duration: 232,
    genre: 'R&B',
    year: 2022,
  },
  {
    title: 'About Damn Time',
    artist: 'Lizzo',
    album: 'Special',
    duration: 185,
    genre: 'Pop',
    year: 2022,
  },
  {
    title: 'Unholy',
    artist: 'Sam Smith & Kim Petras',
    album: 'Gloria',
    duration: 157,
    genre: 'Pop',
    year: 2022,
  },
  {
    title: 'Calm Down',
    artist: 'Rema & Selena Gomez',
    album: 'Rave & Roses',
    duration: 239,
    genre: 'Afrobeats',
    year: 2022,
  },
  {
    title: 'Last Night',
    artist: 'Morgan Wallen',
    album: 'One Thing at a Time',
    duration: 165,
    genre: 'Country',
    year: 2023,
  },
  {
    title: 'Running Up That Hill',
    artist: 'Kate Bush',
    album: 'Hounds of Love',
    duration: 298,
    genre: 'Pop',
    year: 1985,
  },
  {
    title: 'Glimpse of Us',
    artist: 'Joji',
    album: 'SMITHEREENS',
    duration: 213,
    genre: 'Pop',
    year: 2022,
  },
  {
    title: 'Break My Soul',
    artist: 'Beyoncé',
    album: 'RENAISSANCE',
    duration: 278,
    genre: 'Dance',
    year: 2022,
  },
  {
    title: 'Super Freaky Girl',
    artist: 'Nicki Minaj',
    album: 'Pink Friday 2',
    duration: 172,
    genre: 'Hip Hop',
    year: 2022,
  },
  {
    title: 'First Class',
    artist: 'Jack Harlow',
    album: 'Come Home the Kids Miss You',
    duration: 174,
    genre: 'Hip Hop',
    year: 2022,
  },
  {
    title: 'Sunroof',
    artist: 'Nicky Youre & dazy',
    album: 'Sunroof',
    duration: 163,
    genre: 'Pop',
    year: 2022,
  },
  {
    title: 'I Like You',
    artist: 'Post Malone ft. Doja Cat',
    album: 'Twelve Carat Toothache',
    duration: 193,
    genre: 'Pop',
    year: 2022,
  },
  {
    title: 'Big Energy',
    artist: 'Latto',
    album: '777',
    duration: 173,
    genre: 'Hip Hop',
    year: 2022,
  },
  {
    title: 'Boyfriend',
    artist: 'Dove Cameron',
    album: 'Boyfriend',
    duration: 153,
    genre: 'Pop',
    year: 2022,
  },
  {
    title: 'Woman',
    artist: 'Doja Cat',
    album: 'Planet Her',
    duration: 172,
    genre: 'Pop',
    year: 2021,
  },
  {
    title: 'Industry Baby',
    artist: 'Lil Nas X & Jack Harlow',
    album: 'MONTERO',
    duration: 212,
    genre: 'Hip Hop',
    year: 2021,
  },
  {
    title: 'Wait For U',
    artist: 'Future ft. Drake & Tems',
    album: 'I NEVER LIKED YOU',
    duration: 189,
    genre: 'Hip Hop',
    year: 2022,
  },
  {
    title: 'Ghost',
    artist: 'Justin Bieber',
    album: 'Justice',
    duration: 153,
    genre: 'Pop',
    year: 2021,
  },
  {
    title: 'Late Night Talking',
    artist: 'Harry Styles',
    album: "Harry's House",
    duration: 177,
    genre: 'Pop',
    year: 2022,
  },
  {
    title: 'Something in the Orange',
    artist: 'Zach Bryan',
    album: 'American Heartbreak',
    duration: 234,
    genre: 'Country',
    year: 2022,
  },
  {
    title: 'Unstoppable',
    artist: 'Sia',
    album: 'This Is Acting',
    duration: 217,
    genre: 'Pop',
    year: 2016,
  },
  {
    title: 'Until I Found You',
    artist: 'Stephen Sanchez',
    album: 'Angel Face',
    duration: 177,
    genre: 'Pop',
    year: 2022,
  },
  {
    title: 'Left and Right',
    artist: 'Charlie Puth ft. Jung Kook',
    album: 'CHARLIE',
    duration: 155,
    genre: 'Pop',
    year: 2022,
  },
  {
    title: 'Wasted on You',
    artist: 'Morgan Wallen',
    album: 'One Thing at a Time',
    duration: 178,
    genre: 'Country',
    year: 2023,
  },
  {
    title: 'Tití Me Preguntó',
    artist: 'Bad Bunny',
    album: 'Un Verano Sin Ti',
    duration: 243,
    genre: 'Latin',
    year: 2022,
  },
  {
    title: 'Ella Baila Sola',
    artist: 'Eslabon Armado & Peso Pluma',
    album: 'DESVELADO',
    duration: 165,
    genre: 'Regional Mexican',
    year: 2023,
  },
  {
    title: 'Boys a Liar Pt. 2',
    artist: 'PinkPantheress & Ice Spice',
    album: 'Boys a Liar Pt. 2',
    duration: 131,
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'Paint the Town Red',
    artist: 'Doja Cat',
    album: 'Scarlet',
    duration: 231,
    genre: 'Hip Hop',
    year: 2023,
  },
  {
    title: 'Fast Car',
    artist: 'Luke Combs',
    album: "Gettin' Old",
    duration: 265,
    genre: 'Country',
    year: 2023,
  },
  {
    title: 'What Was I Made For?',
    artist: 'Billie Eilish',
    album: 'Barbie: The Album',
    duration: 222,
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'Rich Men North of Richmond',
    artist: 'Oliver Anthony Music',
    album: 'Rich Men North of Richmond',
    duration: 187,
    genre: 'Folk',
    year: 2023,
  },
  {
    title: 'I Remember Everything',
    artist: 'Zach Bryan ft. Kacey Musgraves',
    album: 'Zach Bryan',
    duration: 227,
    genre: 'Country',
    year: 2023,
  },
  {
    title: 'Thinkin Bout Me',
    artist: 'Morgan Wallen',
    album: 'One Thing at a Time',
    duration: 177,
    genre: 'Country',
    year: 2023,
  },
  {
    title: 'Fukumean',
    artist: 'Gunna',
    album: 'a Gift & a Curse',
    duration: 158,
    genre: 'Hip Hop',
    year: 2023,
  },
  {
    title: 'Dance the Night',
    artist: 'Dua Lipa',
    album: 'Barbie: The Album',
    duration: 177,
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'Barbie World',
    artist: 'Nicki Minaj & Ice Spice',
    album: 'Barbie: The Album',
    duration: 110,
    genre: 'Hip Hop',
    year: 2023,
  },
  {
    title: 'Seven',
    artist: 'Jung Kook ft. Latto',
    album: 'Seven',
    duration: 185,
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'Popular',
    artist: 'The Weeknd, Playboi Carti & Madonna',
    album: 'The Idol',
    duration: 215,
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'Meltdown',
    artist: 'Travis Scott ft. Drake',
    album: 'UTOPIA',
    duration: 247,
    genre: 'Hip Hop',
    year: 2023,
  },
  {
    title: 'Feather',
    artist: 'Sabrina Carpenter',
    album: "emails i can't send fwd:",
    duration: 185,
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'Get Him Back!',
    artist: 'Olivia Rodrigo',
    album: 'GUTS',
    duration: 191,
    genre: 'Pop Rock',
    year: 2023,
  },
  {
    title: 'Used to Be Young',
    artist: 'Miley Cyrus',
    album: 'Used to Be Young',
    duration: 191,
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'Bad Idea Right?',
    artist: 'Olivia Rodrigo',
    album: 'GUTS',
    duration: 184,
    genre: 'Pop Rock',
    year: 2023,
  },
  {
    title: 'Better Place',
    artist: '*NSYNC',
    album: 'Trolls Band Together',
    duration: 123,
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'Need a Favor',
    artist: 'Jelly Roll',
    album: 'Whitsitt Chapel',
    duration: 205,
    genre: 'Country',
    year: 2023,
  },
  {
    title: 'Calling',
    artist: 'Metro Boomin ft. Swae Lee & NAV',
    album: 'Spider-Man: Across the Spider-Verse',
    duration: 218,
    genre: 'Hip Hop',
    year: 2023,
  },
  {
    title: 'Lovin on Me',
    artist: 'Jack Harlow',
    album: 'Lovin on Me',
    duration: 139,
    genre: 'Hip Hop',
    year: 2023,
  },
  { title: 'Water', artist: 'Tyla', album: 'Water', duration: 200, genre: 'Afrobeats', year: 2023 },
  {
    title: 'Agora Hills',
    artist: 'Doja Cat',
    album: 'Scarlet',
    duration: 265,
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'Strangers',
    artist: 'Kenya Grace',
    album: 'Strangers',
    duration: 173,
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'My Love Mine All Mine',
    artist: 'Mitski',
    album: 'The Land Is Inhospitable and So Are We',
    duration: 144,
    genre: 'Indie Pop',
    year: 2023,
  },
  {
    title: 'Greedy',
    artist: 'Tate McRae',
    album: 'Greedy',
    duration: 132,
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'Houdini',
    artist: 'Dua Lipa',
    album: 'Houdini',
    duration: 186,
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'Lose Control',
    artist: 'Teddy Swims',
    album: "I've Tried Everything but Therapy",
    duration: 210,
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'Is It Over Now?',
    artist: 'Taylor Swift',
    album: "1989 (Taylor's Version)",
    duration: 229,
    genre: 'Pop',
    year: 2023,
  },
  {
    title: "Now That We Don't Talk",
    artist: 'Taylor Swift',
    album: "1989 (Taylor's Version)",
    duration: 146,
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'Slime You Out',
    artist: 'Drake ft. SZA',
    album: 'For All the Dogs',
    duration: 310,
    genre: 'Hip Hop',
    year: 2023,
  },
  {
    title: 'Daylight',
    artist: 'David Kushner',
    album: 'Daylight',
    duration: 213,
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'cardigan',
    artist: 'Taylor Swift',
    album: 'folklore',
    duration: 239,
    genre: 'Indie Folk',
    year: 2020,
  },
  {
    title: 'august',
    artist: 'Taylor Swift',
    album: 'folklore',
    duration: 261,
    genre: 'Indie Folk',
    year: 2020,
  },
  {
    title: 'Espresso',
    artist: 'Sabrina Carpenter',
    album: 'Espresso',
    duration: 175,
    genre: 'Pop',
    year: 2024,
  },
  {
    title: 'Beautiful Things',
    artist: 'Benson Boone',
    album: 'Beautiful Things',
    duration: 181,
    genre: 'Pop',
    year: 2024,
  },
  {
    title: 'Not Like Us',
    artist: 'Kendrick Lamar',
    album: 'Not Like Us',
    duration: 274,
    genre: 'Hip Hop',
    year: 2024,
  },
  {
    title: 'I Had Some Help',
    artist: 'Post Malone ft. Morgan Wallen',
    album: 'I Had Some Help',
    duration: 178,
    genre: 'Country',
    year: 2024,
  },
  {
    title: 'A Bar Song (Tipsy)',
    artist: 'Shaboozey',
    album: 'A Bar Song (Tipsy)',
    duration: 178,
    genre: 'Country',
    year: 2024,
  },
  {
    title: 'Million Dollar Baby',
    artist: 'Tommy Richman',
    album: 'Million Dollar Baby',
    duration: 153,
    genre: 'Hip Hop',
    year: 2024,
  },
  {
    title: 'BIRDS OF A FEATHER',
    artist: 'Billie Eilish',
    album: 'HIT ME HARD AND SOFT',
    duration: 215,
    genre: 'Pop',
    year: 2024,
  },
  {
    title: 'Too Sweet',
    artist: 'Hozier',
    album: 'Unheard',
    duration: 252,
    genre: 'Indie Rock',
    year: 2024,
  },
  {
    title: 'Please Please Please',
    artist: 'Sabrina Carpenter',
    album: 'Please Please Please',
    duration: 186,
    genre: 'Pop',
    year: 2024,
  },
  {
    title: 'Fortnight',
    artist: 'Taylor Swift ft. Post Malone',
    album: 'THE TORTURED POETS DEPARTMENT',
    duration: 228,
    genre: 'Pop',
    year: 2024,
  },
  {
    title: 'Good Luck, Babe!',
    artist: 'Chappell Roan',
    album: 'Good Luck, Babe!',
    duration: 218,
    genre: 'Pop',
    year: 2024,
  },
  {
    title: 'Stick Season',
    artist: 'Noah Kahan',
    album: 'Stick Season',
    duration: 182,
    genre: 'Folk Pop',
    year: 2022,
  },
  {
    title: 'Lil Boo Thang',
    artist: 'Paul Russell',
    album: 'Lil Boo Thang',
    duration: 114,
    genre: 'Pop',
    year: 2023,
  },
  {
    title: "we can't be friends",
    artist: 'Ariana Grande',
    album: 'eternal sunshine',
    duration: 228,
    genre: 'Pop',
    year: 2024,
  },
  { title: 'Saturn', artist: 'SZA', album: 'Saturn', duration: 186, genre: 'R&B', year: 2024 },
  {
    title: "TEXAS HOLD 'EM",
    artist: 'Beyoncé',
    album: 'COWBOY CARTER',
    duration: 233,
    genre: 'Country',
    year: 2024,
  },
  {
    title: 'Like That',
    artist: 'Future, Metro Boomin & Kendrick Lamar',
    album: "WE DON'T TRUST YOU",
    duration: 267,
    genre: 'Hip Hop',
    year: 2024,
  },
  {
    title: 'LUNCH',
    artist: 'Billie Eilish',
    album: 'HIT ME HARD AND SOFT',
    duration: 180,
    genre: 'Pop',
    year: 2024,
  },
  {
    title: 'Pink Skies',
    artist: 'Zach Bryan',
    album: 'Pink Skies',
    duration: 212,
    genre: 'Country',
    year: 2024,
  },
  {
    title: 'Slow It Down',
    artist: 'Benson Boone',
    album: 'Fireworks & Rollerblades',
    duration: 173,
    genre: 'Pop',
    year: 2024,
  },
  {
    title: 'Austin',
    artist: 'Dasha',
    album: 'Austin',
    duration: 171,
    genre: 'Country',
    year: 2024,
  },
  {
    title: 'I Can Do It With a Broken Heart',
    artist: 'Taylor Swift',
    album: 'THE TORTURED POETS DEPARTMENT',
    duration: 218,
    genre: 'Pop',
    year: 2024,
  },
  {
    title: 'One of the Girls',
    artist: 'The Weeknd, JENNIE & Lily-Rose Depp',
    album: 'The Idol',
    duration: 244,
    genre: 'R&B',
    year: 2023,
  },
  {
    title: 'End of Beginning',
    artist: 'Djo',
    album: 'DECIDE',
    duration: 158,
    genre: 'Alternative',
    year: 2022,
  },
  {
    title: 'Where the Wild Things Are',
    artist: 'Luke Combs',
    album: "Gettin' Old",
    duration: 218,
    genre: 'Country',
    year: 2023,
  },
  { title: 'Snooze', artist: 'SZA', album: 'SOS', duration: 201, genre: 'R&B', year: 2022 },
  {
    title: 'Sure Thing',
    artist: 'Miguel',
    album: 'All I Want Is You',
    duration: 195,
    genre: 'R&B',
    year: 2010,
  },
  {
    title: 'Favorite Song',
    artist: 'Toosii',
    album: 'NAUJOUR',
    duration: 208,
    genre: 'Hip Hop',
    year: 2023,
  },
  {
    title: 'Area Codes',
    artist: 'Kaliii',
    album: 'Area Codes',
    duration: 139,
    genre: 'Hip Hop',
    year: 2023,
  },
  {
    title: 'Players',
    artist: 'Coi Leray',
    album: 'Players',
    duration: 140,
    genre: 'Hip Hop',
    year: 2023,
  },
  {
    title: 'Deli',
    artist: 'Ice Spice',
    album: 'Like..?',
    duration: 126,
    genre: 'Hip Hop',
    year: 2023,
  },
  {
    title: 'Demons',
    artist: 'Doja Cat',
    album: 'Scarlet',
    duration: 195,
    genre: 'Pop',
    year: 2023,
  },
  {
    title: "Say Don't Go",
    artist: 'Taylor Swift',
    album: "1989 (Taylor's Version)",
    duration: 261,
    genre: 'Pop',
    year: 2023,
  },
  {
    title: 'Style',
    artist: 'Taylor Swift',
    album: '1989',
    duration: 231,
    genre: 'Pop',
    year: 2014,
  },
  {
    title: 'Die For You',
    artist: 'The Weeknd',
    album: 'Starboy',
    duration: 260,
    genre: 'R&B',
    year: 2016,
  },
  {
    title: "Creepin'",
    artist: 'Metro Boomin, The Weeknd & 21 Savage',
    album: 'HEROES & VILLAINS',
    duration: 222,
    genre: 'R&B',
    year: 2022,
  },
  {
    title: 'Rich Flex',
    artist: 'Drake & 21 Savage',
    album: 'Her Loss',
    duration: 239,
    genre: 'Hip Hop',
    year: 2022,
  },
  {
    title: 'Just Wanna Rock',
    artist: 'Lil Uzi Vert',
    album: 'Just Wanna Rock',
    duration: 123,
    genre: 'Hip Hop',
    year: 2022,
  },
  {
    title: 'Jimmy Cooks',
    artist: 'Drake ft. 21 Savage',
    album: 'Honestly, Nevermind',
    duration: 218,
    genre: 'Hip Hop',
    year: 2022,
  },
  {
    title: 'The Kind of Love We Make',
    artist: 'Luke Combs',
    album: "Growin' Up",
    duration: 228,
    genre: 'Country',
    year: 2022,
  },
  {
    title: 'Rock and a Hard Place',
    artist: 'Bailey Zimmerman',
    album: 'Religiously. The Album.',
    duration: 207,
    genre: 'Country',
    year: 2022,
  },
  {
    title: 'You Proof',
    artist: 'Morgan Wallen',
    album: 'One Thing at a Time',
    duration: 157,
    genre: 'Country',
    year: 2022,
  },
  {
    title: 'She Likes It',
    artist: 'Russell Dickerson ft. Jake Scott',
    album: 'She Likes It',
    duration: 175,
    genre: 'Country',
    year: 2022,
  },
  {
    title: 'Tukoh Taka',
    artist: 'Nicki Minaj, Maluma & Myriam Fares',
    album: 'Tukoh Taka',
    duration: 135,
    genre: 'Pop',
    year: 2022,
  },
  {
    title: 'Woman',
    artist: 'Doja Cat',
    album: 'Planet Her',
    duration: 172,
    genre: 'Pop',
    year: 2021,
  },
  {
    title: 'Vegas',
    artist: 'Doja Cat',
    album: 'Vegas',
    duration: 183,
    genre: 'Hip Hop',
    year: 2022,
  },
  {
    title: 'Candle in the Wind',
    artist: 'Elton John',
    album: 'Goodbye Yellow Brick Road',
    duration: 229,
    genre: 'Pop',
    year: 1973,
  },
  {
    title: 'White Christmas',
    artist: 'Bing Crosby',
    album: 'White Christmas',
    duration: 181,
    genre: 'Holiday',
    year: 1942,
  },
  {
    title: 'Macarena',
    artist: 'Los Del Rio',
    album: 'A mí me gusta',
    duration: 250,
    genre: 'Latin Pop',
    year: 1993,
  },
  {
    title: 'Physical',
    artist: 'Dua Lipa',
    album: 'Future Nostalgia',
    duration: 193,
    genre: 'Pop',
    year: 2020,
  },
  {
    title: "Don't Start Now",
    artist: 'Dua Lipa',
    album: 'Future Nostalgia',
    duration: 183,
    genre: 'Pop',
    year: 2019,
  },
  {
    title: 'Circles',
    artist: 'Post Malone',
    album: "Hollywood's Bleeding",
    duration: 215,
    genre: 'Pop',
    year: 2019,
  },
  {
    title: 'Memories',
    artist: 'Maroon 5',
    album: 'JORDI',
    duration: 189,
    genre: 'Pop',
    year: 2019,
  },
  {
    title: 'Bad Guy',
    artist: 'Billie Eilish',
    album: 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?',
    duration: 194,
    genre: 'Pop',
    year: 2019,
  },
  {
    title: 'Truth Hurts',
    artist: 'Lizzo',
    album: 'Cuz I Love You',
    duration: 173,
    genre: 'Pop',
    year: 2019,
  },
  {
    title: 'Thank U, Next',
    artist: 'Ariana Grande',
    album: 'thank u, next',
    duration: 207,
    genre: 'Pop',
    year: 2019,
  },
  {
    title: '7 Rings',
    artist: 'Ariana Grande',
    album: 'thank u, next',
    duration: 178,
    genre: 'Pop',
    year: 2019,
  },
  {
    title: 'High Hopes',
    artist: 'Panic! At The Disco',
    album: 'Pray for the Wicked',
    duration: 190,
    genre: 'Pop Rock',
    year: 2018,
  },
  {
    title: 'Girls Like You',
    artist: 'Maroon 5 ft. Cardi B',
    album: 'Red Pill Blues',
    duration: 235,
    genre: 'Pop',
    year: 2018,
  },
  {
    title: "God's Plan",
    artist: 'Drake',
    album: 'Scorpion',
    duration: 199,
    genre: 'Hip Hop',
    year: 2018,
  },
  {
    title: 'Perfect',
    artist: 'Ed Sheeran',
    album: '÷ (Divide)',
    duration: 263,
    genre: 'Pop',
    year: 2017,
  },
  {
    title: 'Havana',
    artist: 'Camila Cabello ft. Young Thug',
    album: 'Camila',
    duration: 217,
    genre: 'Pop',
    year: 2017,
  },
  {
    title: 'Closer',
    artist: 'The Chainsmokers ft. Halsey',
    album: 'Collage',
    duration: 244,
    genre: 'Electronic',
    year: 2016,
  },
  {
    title: 'Love Yourself',
    artist: 'Justin Bieber',
    album: 'Purpose',
    duration: 233,
    genre: 'Pop',
    year: 2015,
  },
  {
    title: 'Sorry',
    artist: 'Justin Bieber',
    album: 'Purpose',
    duration: 200,
    genre: 'Pop',
    year: 2015,
  },
  { title: 'Hello', artist: 'Adele', album: '25', duration: 295, genre: 'Pop', year: 2015 },
  {
    title: 'Thinking Out Loud',
    artist: 'Ed Sheeran',
    album: '×',
    duration: 281,
    genre: 'Pop',
    year: 2014,
  },
  {
    title: 'All of Me',
    artist: 'John Legend',
    album: 'Love in the Future',
    duration: 269,
    genre: 'R&B',
    year: 2013,
  },
  {
    title: 'Radioactive',
    artist: 'Imagine Dragons',
    album: 'Night Visions',
    duration: 186,
    genre: 'Alternative Rock',
    year: 2012,
  },
  {
    title: 'Somebody That I Used to Know',
    artist: 'Gotye ft. Kimbra',
    album: 'Making Mirrors',
    duration: 244,
    genre: 'Indie Pop',
    year: 2011,
  },
  {
    title: 'We Found Love',
    artist: 'Rihanna ft. Calvin Harris',
    album: 'Talk That Talk',
    duration: 215,
    genre: 'Pop',
    year: 2011,
  },
  {
    title: 'Grenade',
    artist: 'Bruno Mars',
    album: 'Doo-Wops & Hooligans',
    duration: 222,
    genre: 'Pop',
    year: 2010,
  },
  {
    title: 'Firework',
    artist: 'Katy Perry',
    album: 'Teenage Dream',
    duration: 227,
    genre: 'Pop',
    year: 2010,
  },
  {
    title: 'Empire State of Mind',
    artist: 'Jay-Z & Alicia Keys',
    album: 'The Blueprint 3',
    duration: 276,
    genre: 'Hip Hop',
    year: 2009,
  },
  {
    title: 'Poker Face',
    artist: 'Lady Gaga',
    album: 'The Fame',
    duration: 237,
    genre: 'Pop',
    year: 2008,
  },
  {
    title: 'Viva La Vida',
    artist: 'Coldplay',
    album: 'Viva la Vida or Death and All His Friends',
    duration: 242,
    genre: 'Alternative Rock',
    year: 2008,
  },
  {
    title: 'Umbrella',
    artist: 'Rihanna ft. Jay-Z',
    album: 'Good Girl Gone Bad',
    duration: 256,
    genre: 'R&B',
    year: 2007,
  },
  {
    title: 'Crazy in Love',
    artist: 'Beyoncé ft. Jay-Z',
    album: 'Dangerously in Love',
    duration: 236,
    genre: 'R&B',
    year: 2003,
  },
  {
    title: 'In Da Club',
    artist: '50 Cent',
    album: "Get Rich or Die Tryin'",
    duration: 193,
    genre: 'Hip Hop',
    year: 2003,
  },
  {
    title: 'Hot in Herre',
    artist: 'Nelly',
    album: 'Nellyville',
    duration: 229,
    genre: 'Hip Hop',
    year: 2002,
  },
  {
    title: "Fallin'",
    artist: 'Alicia Keys',
    album: 'Songs in A Minor',
    duration: 210,
    genre: 'R&B',
    year: 2001,
  },
  {
    title: 'Oops!... I Did It Again',
    artist: 'Britney Spears',
    album: 'Oops!... I Did It Again',
    duration: 211,
    genre: 'Pop',
    year: 2000,
  },
  {
    title: 'Say My Name',
    artist: "Destiny's Child",
    album: "The Writing's on the Wall",
    duration: 271,
    genre: 'R&B',
    year: 1999,
  },
  { title: 'Believe', artist: 'Cher', album: 'Believe', duration: 238, genre: 'Pop', year: 1998 },
  {
    title: 'My Heart Will Go On',
    artist: 'Céline Dion',
    album: "Let's Talk About Love",
    duration: 280,
    genre: 'Pop',
    year: 1997,
  },
  {
    title: 'Wannabe',
    artist: 'Spice Girls',
    album: 'Spice',
    duration: 172,
    genre: 'Pop',
    year: 1996,
  },
  {
    title: "Gangsta's Paradise",
    artist: 'Coolio ft. L.V.',
    album: "Gangsta's Paradise",
    duration: 241,
    genre: 'Hip Hop',
    year: 1995,
  },
  {
    title: 'Waterfalls',
    artist: 'TLC',
    album: 'CrazySexyCool',
    duration: 199,
    genre: 'R&B',
    year: 1994,
  },
  {
    title: 'The Sign',
    artist: 'Ace of Base',
    album: 'The Sign',
    duration: 191,
    genre: 'Pop',
    year: 1993,
  },
  {
    title: 'I Will Always Love You',
    artist: 'Whitney Houston',
    album: 'The Bodyguard',
    duration: 273,
    genre: 'R&B',
    year: 1992,
  },
  {
    title: 'Smells Like Teen Spirit',
    artist: 'Nirvana',
    album: 'Nevermind',
    duration: 301,
    genre: 'Rock',
    year: 1991,
  },
  {
    title: 'Nothing Compares 2 U',
    artist: "Sinéad O'Connor",
    album: "I Do Not Want What I Haven't Got",
    duration: 310,
    genre: 'Pop',
    year: 1990,
  },
  {
    title: 'Like a Prayer',
    artist: 'Madonna',
    album: 'Like a Prayer',
    duration: 341,
    genre: 'Pop',
    year: 1989,
  },
  {
    title: "Sweet Child O' Mine",
    artist: "Guns N' Roses",
    album: 'Appetite for Destruction',
    duration: 356,
    genre: 'Rock',
    year: 1987,
  },
  {
    title: "Livin' on a Prayer",
    artist: 'Bon Jovi',
    album: 'Slippery When Wet',
    duration: 249,
    genre: 'Rock',
    year: 1986,
  },
  {
    title: 'Careless Whisper',
    artist: 'George Michael',
    album: 'Make It Big',
    duration: 384,
    genre: 'Pop',
    year: 1984,
  },
  {
    title: 'Billie Jean',
    artist: 'Michael Jackson',
    album: 'Thriller',
    duration: 293,
    genre: 'Pop',
    year: 1983,
  },
  {
    title: 'Every Breath You Take',
    artist: 'The Police',
    album: 'Synchronicity',
    duration: 253,
    genre: 'Rock',
    year: 1983,
  },
  {
    title: 'Purple Rain',
    artist: 'Prince',
    album: 'Purple Rain',
    duration: 521,
    genre: 'R&B',
    year: 1984,
  },
  {
    title: 'Like a Rolling Stone',
    artist: 'Bob Dylan',
    album: 'Highway 61 Revisited',
    duration: 373,
    genre: 'Rock',
    year: 1965,
  },
  {
    title: 'Hotel California',
    artist: 'Eagles',
    album: 'Hotel California',
    duration: 391,
    genre: 'Rock',
    year: 1977,
  },
  {
    title: 'Imagine',
    artist: 'John Lennon',
    album: 'Imagine',
    duration: 187,
    genre: 'Pop',
    year: 1971,
  },
  {
    title: 'Stairway to Heaven',
    artist: 'Led Zeppelin',
    album: 'Led Zeppelin IV',
    duration: 482,
    genre: 'Rock',
    year: 1971,
  },
  {
    title: "What's Going On",
    artist: 'Marvin Gaye',
    album: "What's Going On",
    duration: 230,
    genre: 'R&B',
    year: 1971,
  },
  {
    title: 'Respect',
    artist: 'Aretha Franklin',
    album: 'I Never Loved a Man the Way I Love You',
    duration: 149,
    genre: 'R&B',
    year: 1967,
  },
  {
    title: 'God Only Knows',
    artist: 'The Beach Boys',
    album: 'Pet Sounds',
    duration: 171,
    genre: 'Pop',
    year: 1966,
  },
  {
    title: 'Yesterday',
    artist: 'The Beatles',
    album: 'Help!',
    duration: 125,
    genre: 'Rock',
    year: 1965,
  },
];
